import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Flex, Layout } from "antd";
import { Content, Header } from "antd/es/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pretectum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Flex gap="middle" wrap="wrap">
            <Layout>
              <Header className="bg-[#78C2FA] text-white text-2xl/[64px]">
                Pretectum
              </Header>
              <Content className="p-3">
                {children}
              </Content>
            </Layout>
          </Flex>
        </AntdRegistry>
      </body>
    </html>
  );
}
